# Extract Filter Parameters From Munich CKAN Resources

This notebook scans parsable resources from the Munich Open Data CKAN portal and creates a catalog of possible dataframe/API filter parameters.

The output is intended for training-data generation. It answers questions like:

- which datasets/resources can be parsed into a dataframe?
- which columns can the model use as filter parameters?
- which operators are valid for each column?
- which filters can be pushed to CKAN datastore APIs vs applied locally after parsing CSV/XML/HTML?

Important distinction:

- `datastore_active=True`: filters can usually be pushed to CKAN via `datastore_search(filters=...)`.
- CSV/XML/HTML resources: filters are dataframe parameters for local filtering after the file has been parsed.

In [1]:
from __future__ import annotations

import json
import re
import time
import xml.etree.ElementTree as ET
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path
from typing import Any
from urllib.error import HTTPError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

import pandas as pd

pd.set_option("display.max_columns", 120)
pd.set_option("display.max_colwidth", 160)

BASE_URL = "https://opendata.muenchen.de/api/3/action"
USER_AGENT = "smolnalysis-filter-parameter-extractor/0.1"

RAW_DATA_DIR = Path("../training/data/raw")
GENERATED_DATA_DIR = Path("../training/data/generated")
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
GENERATED_DATA_DIR.mkdir(parents=True, exist_ok=True)

MAX_PACKAGES = 100
PAGE_SIZE = 20
SAMPLE_LIMIT = 500
MAX_EXAMPLE_VALUES = 25

PARSABLE_FORMATS = {"csv", "txt", "xml", "rdf", "rss", "atom", "html", "htm"}

BASE_URL

'https://opendata.muenchen.de/api/3/action'

## CKAN and parsing helpers

In [2]:
def ckan_action(action: str, params: dict[str, Any] | None = None, sleep_s: float = 0.0) -> Any:
    params = params or {}
    query = f"?{urlencode(params, doseq=True)}" if params else ""
    url = f"{BASE_URL}/{action}{query}"
    request = Request(url, headers={"User-Agent": USER_AGENT})

    try:
        with urlopen(request, timeout=45) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError({"url": url, "status": exc.code, "body": body[:2000]}) from exc

    if not payload.get("success"):
        raise RuntimeError({"action": action, "params": params, "error": payload.get("error")})

    if sleep_s:
        time.sleep(sleep_s)

    return payload["result"]


def fetch_text(url: str) -> str:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=45) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def normalize_format(resource: dict[str, Any]) -> str:
    fmt = (resource.get("format") or "").strip().lower()
    url = (resource.get("url") or "").lower()
    if fmt:
        return fmt
    for suffix in ["csv", "txt", "xml", "rdf", "rss", "atom", "html", "htm"]:
        if url.endswith(f".{suffix}"):
            return suffix
    return ""

In [3]:
class SimpleHTMLTableParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.tables: list[list[list[str]]] = []
        self._table: list[list[str]] | None = None
        self._row: list[str] | None = None
        self._cell: list[str] | None = None
        self._in_cell = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "table":
            self._table = []
        elif tag == "tr" and self._table is not None:
            self._row = []
        elif tag in {"td", "th"} and self._row is not None:
            self._cell = []
            self._in_cell = True

    def handle_data(self, data: str) -> None:
        if self._in_cell and self._cell is not None:
            text = data.strip()
            if text:
                self._cell.append(text)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"td", "th"} and self._row is not None and self._cell is not None:
            self._row.append(" ".join(self._cell).strip())
            self._cell = None
            self._in_cell = False
        elif tag == "tr" and self._table is not None and self._row is not None:
            if self._row:
                self._table.append(self._row)
            self._row = None
        elif tag == "table" and self._table is not None:
            if self._table:
                self.tables.append(self._table)
            self._table = None


def flatten_xml_element(element: ET.Element) -> dict[str, Any]:
    row: dict[str, Any] = dict(element.attrib)
    for child in list(element):
        key = child.tag.split("}")[-1]
        value = (child.text or "").strip()
        if list(child):
            for nested_key, nested_value in flatten_xml_element(child).items():
                row[f"{key}.{nested_key}"] = nested_value
        elif value:
            row[key] = value
    return row


def parse_html_table(url: str, table_index: int = 0) -> pd.DataFrame:
    parser = SimpleHTMLTableParser()
    parser.feed(fetch_text(url))
    if not parser.tables:
        raise ValueError("No HTML tables found.")
    table = parser.tables[table_index]
    header, rows = table[0], table[1:]
    width = len(header)
    normalized = [row[:width] + [None] * max(0, width - len(row)) for row in rows]
    return pd.DataFrame(normalized, columns=header)


def parse_xml(url: str, limit: int = SAMPLE_LIMIT) -> pd.DataFrame:
    root = ET.fromstring(fetch_text(url))
    rows = []
    for element in root.iter():
        if list(element):
            row = flatten_xml_element(element)
            if row:
                rows.append(row)
        if len(rows) >= limit:
            break
    if not rows:
        rows = [flatten_xml_element(root)]
    return pd.DataFrame(rows).head(limit)

## Resource sampler

For datastore resources, the field metadata comes from CKAN and filters can be server-side. For file resources, the notebook parses a sample into pandas and derives filter parameters from dataframe columns.

In [4]:
def sample_resource(resource: dict[str, Any], limit: int = SAMPLE_LIMIT) -> tuple[pd.DataFrame, dict[str, Any]]:
    metadata = {
        "filter_mode": "local_dataframe",
        "server_filter_supported": False,
        "source": "file",
    }

    if resource.get("datastore_active"):
        result = ckan_action("datastore_search", {"resource_id": resource["id"], "limit": limit})
        metadata.update({
            "filter_mode": "ckan_datastore",
            "server_filter_supported": True,
            "source": "datastore_search",
            "ckan_fields": result.get("fields", []),
        })
        return pd.DataFrame(result.get("records", [])), metadata

    url = resource.get("url")
    fmt = normalize_format(resource)
    if not url:
        raise ValueError("Resource has no URL.")

    if fmt in {"csv", "txt"}:
        return pd.read_csv(url, sep=None, engine="python", nrows=limit), metadata
    if fmt in {"xml", "rdf", "rss", "atom"} or url.lower().endswith(".xml"):
        return parse_xml(url, limit=limit), metadata
    if fmt in {"html", "htm"} or url.lower().endswith((".html", ".htm")):
        return parse_html_table(url).head(limit), metadata

    raise ValueError(f"Unsupported format: {resource.get('format')} url={url}")

## Filter-parameter inference

The extractor emits conservative operators. Numeric/date-like columns get range operators. Low-cardinality text/category columns get equality and membership operators. Longer text columns get `contains`.

In [5]:
def clean_examples(values: pd.Series, max_values: int = MAX_EXAMPLE_VALUES) -> list[Any]:
    clean = values.dropna()
    if clean.empty:
        return []
    counts = Counter(clean.astype(str).tolist())
    return [value for value, _ in counts.most_common(max_values)]


def looks_like_year(series: pd.Series) -> bool:
    numeric = pd.to_numeric(series.dropna(), errors="coerce").dropna()
    if numeric.empty:
        return False
    return numeric.between(1800, 2100).mean() > 0.9


def looks_like_date(series: pd.Series) -> bool:
    sample = series.dropna().astype(str).head(50)
    if sample.empty:
        return False
    date_patterns = [
        r"^\d{4}-\d{1,2}-\d{1,2}",
        r"^\d{1,2}\.\d{1,2}\.\d{4}",
        r"^\d{1,2}/\d{1,2}/\d{4}",
    ]
    matches = sample.apply(lambda value: any(re.search(pattern, value) for pattern in date_patterns))
    return matches.mean() > 0.6


def infer_column_kind(series: pd.Series) -> str:
    if pd.api.types.is_bool_dtype(series):
        return "boolean"
    if pd.api.types.is_numeric_dtype(series):
        return "year" if looks_like_year(series) else "numeric"
    if looks_like_date(series):
        return "date"

    non_null = series.dropna().astype(str)
    if non_null.empty:
        return "unknown"
    unique_ratio = non_null.nunique() / max(len(non_null), 1)
    avg_len = non_null.str.len().mean()
    if unique_ratio <= 0.3 or non_null.nunique() <= 50:
        return "category"
    if avg_len > 30:
        return "text"
    return "string"


def operators_for_kind(kind: str) -> list[str]:
    if kind in {"numeric", "year", "date"}:
        return ["eq", "neq", "gt", "gte", "lt", "lte", "between", "in"]
    if kind in {"category", "boolean", "string"}:
        return ["eq", "neq", "in", "contains"]
    if kind == "text":
        return ["contains", "eq", "neq"]
    return ["eq", "neq"]


def infer_filter_parameters(df: pd.DataFrame, resource_meta: dict[str, Any]) -> list[dict[str, Any]]:
    params = []
    for column in df.columns:
        series = df[column]
        kind = infer_column_kind(series)
        numeric = pd.to_numeric(series.dropna(), errors="coerce") if kind in {"numeric", "year"} else pd.Series(dtype="float64")
        examples = clean_examples(series)
        params.append({
            "column": str(column),
            "dtype": str(series.dtype),
            "kind": kind,
            "operators": operators_for_kind(kind),
            "nullable": bool(series.isna().any()),
            "non_null_count": int(series.notna().sum()),
            "unique_sample_count": int(series.dropna().nunique()),
            "example_values": examples,
            "min": None if numeric.empty else float(numeric.min()),
            "max": None if numeric.empty else float(numeric.max()),
            "filter_mode": resource_meta["filter_mode"],
            "server_filter_supported": resource_meta["server_filter_supported"],
        })
    return params

## Fetch candidate resources

Increase `MAX_PACKAGES` after the first run succeeds. The portal has many resources, and HTML/XML parsing quality varies.

In [6]:
def search_packages(query: str = "", rows: int = PAGE_SIZE, start: int = 0, sleep_s: float = 0.0) -> dict[str, Any]:
    return ckan_action("package_search", {"q": query, "rows": rows, "start": start}, sleep_s=sleep_s)


packages = []
for start in range(0, MAX_PACKAGES, PAGE_SIZE):
    result = search_packages(rows=min(PAGE_SIZE, MAX_PACKAGES - start), start=start, sleep_s=0.1)
    packages.extend(result["results"])

print(f"packages fetched: {len(packages):,}")

candidate_resources = []
for package in packages:
    for resource in package.get("resources", []):
        fmt = normalize_format(resource)
        if resource.get("datastore_active") or fmt in PARSABLE_FORMATS:
            candidate_resources.append({"package": package, "resource": resource, "format": fmt})

print(f"candidate resources: {len(candidate_resources):,}")
pd.DataFrame([
    {
        "package_name": item["package"].get("name"),
        "package_title": item["package"].get("title"),
        "resource_id": item["resource"].get("id"),
        "resource_name": item["resource"].get("name"),
        "format": item["format"],
        "datastore_active": item["resource"].get("datastore_active"),
    }
    for item in candidate_resources
]).head(30)

packages fetched: 100
candidate resources: 349

,package_name,package_title,resource_id,resource_name,format,datastore_active
0,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,True
1,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,False
2,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,a1e527c2-9a8b-4fc3-982a-7889683106f6,Fachportal Energie,html,False
3,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,f0242692-a06d-4908-a12d-fb57211c931a,Open Geodata Portal des Geoportals,html,False
4,enp_baublock_grundwasserpotential_einteilig_25832,Grundwasserpotential,04a6c65d-3b01-4623-9e73-ad6babed6d5c,Metadaten (XML),xml,False
5,enp_baublock_grundwasserpotential_einteilig_25832,Grundwasserpotential,4d0e4d13-14e7-4dad-ab4a-388ea587d676,Fachportal Energie,html,False
6,enp_baublock_grundwasserpotential_einteilig_25832,Grundwasserpotential,edde8548-855f-42bb-8822-f3958407e01d,Open Geodata Portal des Geoportals,html,False
7,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,False
8,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),868191bd-c230-4480-8937-c2c0ebbca8b3,WFS (GML),xml,False
9,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),514acba4-4b57-49a7-9371-7badb8b69038,WFS (CSV),csv,False
10,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),fdb0eca8-9890-4258-9dfa-fd39c1fbbfe8,Open Geodata Portal des Geoportals,html,False
11,bestand_sbh_opendata,Sozialbürgerhaus,84f5b113-63ec-4a9d-a2b2-6c73abb4603a,Metadaten (XML),xml,False
12,bestand_sbh_opendata,Sozialbürgerhaus,c6a707e4-a15d-47fc-85b7-03b5611b5eec,WFS (GML),xml,False
13,bestand_sbh_opendata,Sozialbürgerhaus,20d4fce8-eef4-42c6-89eb-17d54d86a08e,WFS (CSV),csv,False
14,bestand_sbh_opendata,Sozialbürgerhaus,d55bf5b9-b8a7-416f-bc97-64eea3235308,Open Geodata Portal des Geoportals,html,False
15,abfall_gewerbemisch_opendata,Anlagen zur Sortierung von Baustellen- und Gewerbemischabfällen (Opendata),d51b5bba-96b4-477a-b8a6-136292e66cc2,Metadaten (XML),xml,False
16,abfall_gewerbemisch_opendata,Anlagen zur Sortierung von Baustellen- und Gewerbemischabfällen (Opendata),21e64f55-7b96-4a26-baba-aaed970a4d75,WFS (GML),xml,False
17,abfall_gewerbemisch_opendata,Anlagen zur Sortierung von Baustellen- und Gewerbemischabfällen (Opendata),f566d512-0a99-4a65-82a0-a2f80d830ce9,WFS (CSV),csv,False
18,abfall_gewerbemisch_opendata,Anlagen zur Sortierung von Baustellen- und Gewerbemischabfällen (Opendata),4860a2b9-1111-4439-82de-b6903b87e990,Open Geodata Portal des Geoportals,html,False
19,awm_container_barrierefrei,Barrierefreie Container für Altglas,f4f578d8-6e38-41ff-967f-8dc685170784,Fachportal AWM,html,False
20,awm_container_barrierefrei,Barrierefreie Container für Altglas,8229b163-6484-4b2a-98b0-7a1fadb86450,WFS (GML),xml,False
21,awm_container_barrierefrei,Barrierefreie Container für Altglas,6bd384ac-3512-4078-a340-2269dbfe9f3d,WFS (CSV),csv,False
22,awm_container_barrierefrei,Barrierefreie Container für Altglas,bba0cf03-80db-428c-9d44-a8ea2b2cb4f7,Open Geodata Portal des Geoportals,html,False
23,awm_container_barrierefrei,Barrierefreie Container für Altglas,fdbe7355-29cb-473e-af32-ea833fcb068f,Metadaten (XML),xml,False
24,abfall_betrieb_opendata,Abfallentsorgungsanlagen der Landeshauptstadt München,625c53fe-6140-4fd1-aa00-36e6df7c3dd5,Metadaten (XML),xml,False
25,abfall_betrieb_opendata,Abfallentsorgungsanlagen der Landeshauptstadt München,4d2f3244-6e7a-4d8f-8d37-8ada77f511a2,WFS (GML),xml,False
26,abfall_betrieb_opendata,Abfallentsorgungsanlagen der Landeshauptstadt München,d8e80b31-9123-4fb3-aa6e-9fdfec1f02d2,WFS (CSV),csv,False
27,abfall_betrieb_opendata,Abfallentsorgungsanlagen der Landeshauptstadt München,86aca2bb-c82f-45df-9fde-79be674ea36c,Open Geodata Portal des Geoportals,html,False
28,vollst_pflegeeinrichtung_opendata,Vollstationäre Pflegeeinrichtungen,7865cdb7-8375-484c-8a9b-0d5fd37493ac,Metadaten (XML),xml,False
29,vollst_pflegeeinrichtung_opendata,Vollstationäre Pflegeeinrichtungen,aee17334-a9dd-4db7-a7d5-0a4950421ebd,WFS (GML),xml,False

## Extract filter parameters

This cell creates one JSON object per parsable resource. Failed resources are kept with `ok=false` so you can inspect parser gaps.

In [7]:
filter_catalog = []

for index, item in enumerate(candidate_resources, start=1):
    package = item["package"]
    resource = item["resource"]
    fmt = item["format"]
    print(f"[{index}/{len(candidate_resources)}] {package.get('name')} / {resource.get('name')} ({fmt})")

    entry = {
        "ok": False,
        "package_id": package.get("id"),
        "package_name": package.get("name"),
        "package_title": package.get("title"),
        "resource_id": resource.get("id"),
        "resource_name": resource.get("name"),
        "resource_format": fmt,
        "resource_url": resource.get("url"),
        "datastore_active": bool(resource.get("datastore_active")),
        "filter_parameters": [],
        "sample_rows": [],
        "error": None,
    }

    try:
        df, resource_meta = sample_resource(resource, limit=SAMPLE_LIMIT)
        if df.empty:
            raise ValueError("Parsed dataframe is empty.")
        entry.update({
            "ok": True,
            "row_sample_count": int(len(df)),
            "column_count": int(len(df.columns)),
            "filter_mode": resource_meta["filter_mode"],
            "server_filter_supported": resource_meta["server_filter_supported"],
            "filter_parameters": infer_filter_parameters(df, resource_meta),
            "sample_rows": df.head(5).where(pd.notna(df.head(5)), None).to_dict(orient="records"),
        })
    except Exception as exc:
        entry["error"] = str(exc)

    filter_catalog.append(entry)
    time.sleep(0.1)

print("done")
print("ok:", sum(1 for entry in filter_catalog if entry["ok"]))
print("failed:", sum(1 for entry in filter_catalog if not entry["ok"]))

[1/349] indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct / Wohndauer München (csv)
[2/349] solarpotenzial_globalstrahlung_p_02 / Metadaten (XML) (xml)
[3/349] solarpotenzial_globalstrahlung_p_02 / Fachportal Energie (html)
[4/349] solarpotenzial_globalstrahlung_p_02 / Open Geodata Portal des Geoportals (html)
[5/349] enp_baublock_grundwasserpotential_einteilig_25832 / Metadaten (XML) (xml)
[6/349] enp_baublock_grundwasserpotential_einteilig_25832 / Fachportal Energie (html)
[7/349] enp_baublock_grundwasserpotential_einteilig_25832 / Open Geodata Portal des Geoportals (html)
[8/349] abfall_sonstiges_opendata / Metadaten (XML) (xml)
[9/349] abfall_sonstiges_opendata / WFS (GML) (xml)
[10/349] abfall_sonstiges_opendata / WFS (CSV) (csv)
[11/349] abfall_sonstiges_opendata / Open Geodata Portal des Geoportals (html)
[12/349] bestand_sbh_opendata / Metadaten (XML) (xml)
[13/349] bestand_sbh_opendata / WFS (GML) (xml)
[14/349] bestand_sbh_opendata / WFS (CSV) (csv)
[15/349] bestand_sbh_opendata / Open Geodata Portal des Geoportals (html)
[16/349] abfall_gewerbemisch_opendata / Metadaten (XML) (xml)
[17/349] abfall_gewerbemisch_opendata / WFS (GML) (xml)
[18/349] abfall_gewerbemisch_opendata / WFS (CSV) (csv)
[19/349] abfall_gewerbemisch_opendata / Open Geodata Portal des Geoportals (html)
[20/349] awm_container_barrierefrei / Fachportal AWM (html)
[21/349] awm_container_barrierefrei / WFS (GML) (xml)
[22/349] awm_container_barrierefrei / WFS (CSV) (csv)
[23/349] awm_container_barrierefrei / Open Geodata Portal des Geoportals (html)
[24/349] awm_container_barrierefrei / Metadaten (XML) (xml)
[25/349] abfall_betrieb_opendata / Metadaten (XML) (xml)
[26/349] abfall_betrieb_opendata / WFS (GML) (xml)
[27/349] abfall_betrieb_opendata / WFS (CSV) (csv)
[28/349] abfall_betrieb_opendata / Open Geodata Portal des Geoportals (html)
[29/349] vollst_pflegeeinrichtung_opendata / Metadaten (XML) (xml)
[30/349] vollst_pflegeeinrichtung_opendata / WFS (GML) (xml)
[31/349] vollst_pflegeeinrichtung_opendata / WFS (CSV) (csv)
[32/349] vollst_pflegeeinrichtung_opendata / Open Geodata Portal des Geoportals (html)
[33/349] abfall_papier_opendata / Metadaten (XML) (xml)
[34/349] abfall_papier_opendata / WFS (GML) (xml)
[35/349] abfall_papier_opendata / WFS (CSV) (csv)
[36/349] abfall_papier_opendata / Open Geodata Portal des Geoportals (html)
[37/349] abfall_elektronik_opendata / Metadaten (XML) (xml)
[38/349] abfall_elektronik_opendata / WFS (GML) (xml)
[39/349] abfall_elektronik_opendata / WFS (CSV) (csv)
[40/349] abfall_elektronik_opendata / Open Geodata Portal des Geoportals (html)
[41/349] awm_container_opendata / Fachportal AWM (html)
[42/349] awm_container_opendata / WFS (GML) (xml)
[43/349] awm_container_opendata / WFS (CSV) (csv)
[44/349] awm_container_opendata / Open Geodata Portal des Geoportals (html)
[45/349] awm_container_opendata / Metadaten (XML) (xml)
[46/349] bestand_asz_opendata / Metadaten (XML) (xml)
[47/349] bestand_asz_opendata / WFS (GML) (xml)
[48/349] bestand_asz_opendata / WFS (CSV) (csv)
[49/349] bestand_asz_opendata / Open Geodata Portal des Geoportals (html)
[50/349] abfall_kompost_opendata / Metadaten (XML) (xml)
[51/349] abfall_kompost_opendata / WFS (GML) (xml)
[52/349] abfall_kompost_opendata / WFS (CSV) (csv)
[53/349] abfall_kompost_opendata / Open Geodata Portal des Geoportals (html)
[54/349] lsa_opendata / Metadaten (XML) (xml)
[55/349] lsa_opendata / Open Geodata Portal des Geoportals (html)
[56/349] lsa_opendata / WFS (GML) (xml)
[57/349] lsa_opendata / WFS (CSV) (csv)
[58/349] gebaeude_waermedichte_o_geb_03 / Metadaten (XML) (xml)
[59/349] gebaeude_waermedichte_o_geb_03 / Open Geodata Portal des Geoportals (html)
[60/349] gebaeude_waermedichte_o_geb_03 / Fachportal Energie (html)
[61/349] bestand_nachbarschaftstreffs_opendata / Metadaten (XML) (xml)
[62/349] bestand_nachbarschaftstreffs_opendata / WFS (GML) (xml)
[63/349] bestand_nachbarschaftstreffs_opendata / WFS (CSV) (csv)
[64/349] bestand_nachbarschaftstreffs_opendata / Open Geodata Portal des Geoportals (html)
[65/349] awm_wertstoffhoefe_opendata / Open Geodata Portal des Geoportals (html)
[66/349] awm_wertstoffhoefe_opendata / WFS (CSV) (csv)
[67/349] awm_wertstoffhoefe_opendata / WFS (GML) (xml)
[68/349] awm_wertstoffhoefe_opendata / Fachportal AWM (html)
[69/349] abfall_auto_metall_opendata / Metadaten (XML) (xml)
[70/349] abfall_auto_metall_opendata / WFS (GML) (xml)
[71/349] abfall_auto_metall_opendata / WFS (CSV) (csv)
[72/349] abfall_auto_metall_opendata / Open Geodata Portal des Geoportals (html)
[73/349] maerkte / WFS (GML) (xml)
[74/349] maerkte / WFS (CSV) (csv)
[75/349] maerkte / Metadaten (XML) (xml)
[76/349] erlaeuterung_strassennamen / Metadaten (XML) (xml)
[77/349] erlaeuterung_strassennamen / Open Geodata Portal (html)
[78/349] erlaeuterung_strassennamen / WFS (GML) (xml)
[79/349] erlaeuterung_strassennamen / WFS (CSV) (csv)
[80/349] baut_strassenabschnitte_wu / WFS (GML) (xml)
[81/349] baut_strassenabschnitte_wu / WFS (CSV) (csv)
[82/349] baut_strassenabschnitte_wu / Metadaten (XML) (xml)
[83/349] baut_strassenabschnitte_wu / Open Geodata Portal des Geoportals (html)
[84/349] opendata_trinkwasserbrunnen / WFS (GML) (xml)
[85/349] opendata_trinkwasserbrunnen / WFS (CSV) (csv)
[86/349] opendata_trinkwasserbrunnen / Open Geodata Portal des Geoportals (html)
[87/349] opendata_trinkwasserbrunnen / Metadaten (XML) (xml)
[88/349] wc_finder / Metadaten (XML) (xml)
[89/349] wc_finder / WFS (GML) (xml)
[90/349] wc_finder / WFS (CSV) (csv)
[91/349] wc_finder / Portal (html)
[92/349] wc_finder / Open Geodata Portal des Geoportals (html)
[93/349] baut_blindenleitsystem_altstadt / WFS (CSV) (csv)
[94/349] baut_blindenleitsystem_altstadt / Metadaten (XML) (xml)
[95/349] baut_blindenleitsystem_altstadt / Open Geodata Portal des Geoportals (html)
[96/349] opendata_miv_umweltzone_vz_point / WFS (GML) (xml)
[97/349] opendata_miv_umweltzone_vz_point / WFS (CSV) (csv)
[98/349] opendata_miv_umweltzone_vz_point / Open Geodata Portal des Geoportals (html)
[99/349] opendata_miv_umweltzone_vz_point / Weitere Informationen (html)
[100/349] opendata_miv_umweltzone_vz_point / Metadaten (XML) (xml)
[101/349] opendata_miv_umweltzone_poly / WFS (GML) (xml)
[102/349] opendata_miv_umweltzone_poly / WFS (CSV) (csv)
[103/349] opendata_miv_umweltzone_poly / Open Geodata Portal des Geoportals (html)
[104/349] opendata_miv_umweltzone_poly / Weitere Informationen (html)
[105/349] opendata_miv_umweltzone_poly / Metadaten (XML) (xml)
[106/349] paketboxen / WFS (CSV) (csv)
[107/349] paketboxen / WFS (GML) (xml)
[108/349] paketboxen / Open Geodata Portal des Geoportals (html)
[109/349] paketboxen / Metadaten (XML) (xml)
[110/349] opendata_ruhver_prm_gebiete_poly / WFS (GML) (xml)
[111/349] opendata_ruhver_prm_gebiete_poly / WFS (CSV) (csv)
[112/349] opendata_ruhver_prm_gebiete_poly / Open Geodata Portal des Geoportals (html)
[113/349] opendata_ruhver_prm_gebiete_poly / Metadaten (XML) (xml)
[114/349] opendata_ruhver_parkseiten_laden_liefern_leisten / Metadaten (XML) (xml)
[115/349] opendata_ruhver_parkseiten_laden_liefern_leisten / Open Geodata Portal des Geoportals (html)
[116/349] opendata_ruhver_parkseiten_laden_liefern_leisten / WFS (GML) (xml)
[117/349] opendata_ruhver_parkseiten_laden_liefern_leisten / WFS (CSV) (csv)
[118/349] ruhver_els_saeule_point / WFS (GML) (xml)
[119/349] ruhver_els_saeule_point / WFS (CSV) (csv)
[120/349] ruhver_els_saeule_point / Open Geodata Portal des Geoportals (html)
[121/349] ruhver_els_saeule_point / Metadaten (XML) (xml)
[122/349] g_sensor_3l_zonen / Metadaten (XML) (xml)
[123/349] g_sensor_3l_zonen / Open Geodata Portal (html)
[124/349] g_sensor_3l_zonen / WFS (GML) (xml)
[125/349] g_sensor_3l_zonen / WFS (CSV) (csv)
[126/349] opendata_ruhver_parkseiten_line / WFS (GML) (xml)
[127/349] opendata_ruhver_parkseiten_line / WFS (CSV) (csv)
[128/349] opendata_ruhver_parkseiten_line / Open Geodata Portal des Geoportals (html)
[129/349] opendata_ruhver_parkseiten_line / Metadaten (XML) (xml)
[130/349] opendata_ruhver_lastenradparken_line / WFS (GML) (xml)
[131/349] opendata_ruhver_lastenradparken_line / WFS (CSV) (csv)
[132/349] opendata_ruhver_lastenradparken_line / Open Geodata Portal des Geoportals (html)
[133/349] opendata_ruhver_lastenradparken_line / Metadaten (XML) (xml)
[134/349] ruhver_mim_abstellverbot_ts / WFS (CSV) (csv)
[135/349] ruhver_mim_abstellverbot_ts / WFS (GML) (xml)
[136/349] ruhver_mim_abstellverbot_ts / Open Geodata Portal des Geoportals (html)
[137/349] ruhver_mim_abstellverbot_ts / Metadaten (XML) (xml)
[138/349] ruhver_mim_abstellverbot_ts / Vordefinierte Teilmengen des Datensatzes (html)
[139/349] behindertenparkplaetze / WFS (CSV) (csv)
[140/349] behindertenparkplaetze / WFS (GML) (xml)
[141/349] behindertenparkplaetze / Open Geodata Portal des Geoportals (html)
[142/349] behindertenparkplaetze / Metadaten (XML) (xml)
[143/349] ruhver_mim_abstellfl_ls / WFS (CSV) (csv)
[144/349] ruhver_mim_abstellfl_ls / WFS (GML) (xml)
[145/349] ruhver_mim_abstellfl_ls / Open Geodata Portal des Geoportals (html)
[146/349] ruhver_mim_abstellfl_ls / Metadaten (XML) (xml)
[147/349] ruhver_mim_abstellfl_ls / Vordefinierte Teilmengen des Datensatzes (html)
[148/349] ruhver_mim_fahrverbot_ts / WFS (CSV) (csv)
[149/349] ruhver_mim_fahrverbot_ts / WFS (GML) (xml)
[150/349] ruhver_mim_fahrverbot_ts / Open Geodata Portal des Geoportals (html)
[151/349] ruhver_mim_fahrverbot_ts / Metadaten (XML) (xml)
[152/349] ruhver_mim_fahrverbot_ts / Vordefinierte Teilmengen des Datensatzes (html)
[153/349] ruhver_els_standort_point / WFS (CSV) (csv)
[154/349] ruhver_els_standort_point / Open Geodata Portal des Geoportals (html)
[155/349] ruhver_els_standort_point / Metadaten (XML) (xml)
[156/349] ruhver_els_standort_point / WFS (GML) (xml)
[157/349] ruhver_mim_abstellfl_ms / WFS (CSV) (csv)
[158/349] ruhver_mim_abstellfl_ms / WFS (GML) (xml)
[159/349] ruhver_mim_abstellfl_ms / Open Geodata Portal des Geoportals (html)
[160/349] ruhver_mim_abstellfl_ms / Metadaten (XML) (xml)
[161/349] ruhver_mim_abstellfl_ms / Vordefinierte Teilmengen des Datensatzes (html)
[162/349] ruhver_radservicestation_point / WFS (CSV) (csv)
[163/349] ruhver_radservicestation_point / WFS (GML) (xml)
[164/349] ruhver_radservicestation_point / Open Geodata Portal des Geoportals (html)
[165/349] ruhver_radservicestation_point / Metadaten (XML) (xml)
[166/349] opendata_ruhver_fahrradparken_line / WFS (GML) (xml)
[167/349] opendata_ruhver_fahrradparken_line / WFS (CSV) (csv)
[168/349] opendata_ruhver_fahrradparken_line / Open Geodata Portal des Geoportals (html)
[169/349] opendata_ruhver_fahrradparken_line / Metadaten (XML) (xml)
[170/349] opendata_ruhver_mim_geofence_poly / WFS (CSV) (csv)
[171/349] opendata_ruhver_mim_geofence_poly / WFS (GML) (xml)
[172/349] opendata_ruhver_mim_geofence_poly / Open Geodata Portal des Geoportals (html)
[173/349] opendata_ruhver_mim_geofence_poly / Metadaten (XML) (xml)
[174/349] opendata_ruhver_mim_geofence_poly / Vordefinierte Teilmengen des Datensatzes (html)
[175/349] ruhver_mim_flexzone_myradl / WFS (GML) (xml)
[176/349] ruhver_mim_flexzone_myradl / WFS (CSV) (csv)
[177/349] ruhver_mim_flexzone_myradl / Open Geodata Portal des Geoportals (html)
[178/349] ruhver_mim_flexzone_myradl / Metadaten (XML) (xml)
[179/349] ruhver_carsharing_station / WFS (CSV) (csv)
[180/349] ruhver_carsharing_station / WFS (GML) (xml)
[181/349] ruhver_carsharing_station / Open Geodata Portal des Geoportals (html)
[182/349] ruhver_carsharing_station / Metadaten (XML) (xml)
[183/349] ruhver_carsharing_station / Vordefinierte Teilmengen des Datensatzes (html)
[184/349] ruhver_mim_abstellfl_bs / WFS (CSV) (csv)
[185/349] ruhver_mim_abstellfl_bs / WFS (GML) (xml)
[186/349] ruhver_mim_abstellfl_bs / Open Geodata Portal des Geoportals (html)
[187/349] ruhver_mim_abstellfl_bs / Metadaten (XML) (xml)
[188/349] ruhver_mim_abstellfl_bs / Vordefinierte Teilmengen des Datensatzes (html)
[189/349] ruhver_mim_abstellverbot_bs / WFS (CSV) (csv)
[190/349] ruhver_mim_abstellverbot_bs / WFS (GML) (xml)
[191/349] ruhver_mim_abstellverbot_bs / Open Geodata Portal des Geoportals (html)
[192/349] ruhver_mim_abstellverbot_bs / Metadaten (XML) (xml)
[193/349] ruhver_mim_abstellverbot_bs / Vordefinierte Teilmengen des Datensatzes (html)
[194/349] ruhver_carsharing / WFS (CSV) (csv)
[195/349] ruhver_carsharing / WFS (GML) (xml)
[196/349] ruhver_carsharing / Open Geodata Portal des Geoportals (html)
[197/349] ruhver_carsharing / Metadaten (XML) (xml)
[198/349] ruhver_carsharing / Vordefinierte Teilmengen des Datensatzes (html)
[199/349] opendata_radschnellverb_line / WFS (GML) (xml)
[200/349] opendata_radschnellverb_line / WFS (CSV) (csv)
[201/349] opendata_radschnellverb_line / Open Geodata Portal des Geoportals (html)
[202/349] opendata_radschnellverb_line / Metadaten (XML) (xml)
[203/349] opendata_ruhver_mp_standort_point / Metadaten (XML) (xml)
[204/349] opendata_ruhver_mp_standort_point / WFS (GML) (xml)
[205/349] opendata_ruhver_mp_standort_point / WFS (CSV) (csv)
[206/349] opendata_ruhver_mp_standort_point / Open Geodata Portal des Geoportals (html)
[207/349] opendata_ruhver_mp_standort_point / Fachportal Mobilität (html)
[208/349] opendata_radentscheid_line / Metadaten (XML) (xml)
[209/349] opendata_radentscheid_line / WFS (GML) (xml)
[210/349] opendata_radentscheid_line / WFS (CSV) (csv)
[211/349] opendata_radentscheid_line / Open Geodata Portal des Geoportals (html)
[212/349] ruhver_mim_abstellfl_ts / WFS (CSV) (csv)
[213/349] ruhver_mim_abstellfl_ts / WFS (GML) (xml)
[214/349] ruhver_mim_abstellfl_ts / Open Geodata Portal des Geoportals (html)
[215/349] ruhver_mim_abstellfl_ts / Metadaten (XML) (xml)
[216/349] ruhver_mim_abstellfl_ts / Vordefinierte Teilmengen des Datensatzes (html)
[217/349] rad_gruene_welle / WFS (CSV) (csv)
[218/349] rad_gruene_welle / Open Geodata Portal des Geoportals (html)
[219/349] rad_gruene_welle / Metadaten (XML) (xml)
[220/349] rad_gruene_welle / WFS (GML) (xml)
[221/349] graustufenstadtplan_2024_schriftplatte / WMS (GetCapabilities) (html)
[222/349] graustufenstadtplan_2024_schriftplatte / Metadaten (XML) (xml)
[223/349] opendata_fahrradstrassen_line / WFS (GML) (xml)
[224/349] opendata_fahrradstrassen_line / WFS (CSV) (csv)
[225/349] opendata_fahrradstrassen_line / Open Geodata Portal des Geoportals (html)
[226/349] opendata_fahrradstrassen_line / Metadaten (XML) (xml)
[227/349] opendata_rad_altstadt_radlring_linie / WFS (GML) (xml)
[228/349] opendata_rad_altstadt_radlring_linie / WFS (CSV) (csv)
[229/349] opendata_rad_altstadt_radlring_linie / Open Geodata Portal des Geoportals (html)
[230/349] opendata_rad_altstadt_radlring_linie / Metadaten (XML) (xml)
[231/349] opendata_raddauerzaehlstellen / WFS (CSV) (csv)
[232/349] opendata_raddauerzaehlstellen / WFS (GML) (xml)
[233/349] opendata_raddauerzaehlstellen / Open Geodata Portal des Geoportals (html)
[234/349] opendata_raddauerzaehlstellen / Metadaten (XML) (xml)
[235/349] rad_rsp_radservicestation / WFS (CSV) (csv)
[236/349] rad_rsp_radservicestation / WFS (GML) (xml)
[237/349] rad_rsp_radservicestation / Open Geodata Portal des Geoportals (html)
[238/349] rad_rsp_radservicestation / Metadaten (XML) (xml)
[239/349] rad_rsp_route_line / WFS (CSV) (csv)
[240/349] rad_rsp_route_line / WFS (GML) (xml)
[241/349] rad_rsp_route_line / Open Geodata Portal des Geoportals (html)
[242/349] rad_rsp_route_line / Metadaten (XML) (xml)
[243/349] rad_rsp_radwege_line / WFS (CSV) (csv)
[244/349] rad_rsp_radwege_line / WFS (GML) (xml)
[245/349] rad_rsp_radwege_line / Open Geodata Portal des Geoportals (html)
[246/349] rad_rsp_radwege_line / Metadaten (XML) (xml)
[247/349] rad_rsp_gemradfusswege_line / WFS (CSV) (csv)
[248/349] rad_rsp_gemradfusswege_line / WFS (GML) (xml)
[249/349] rad_rsp_gemradfusswege_line / Open Geodata Portal des Geoportals (html)
[250/349] rad_rsp_gemradfusswege_line / Metadaten (XML) (xml)
[251/349] rad_rsp_radwege_forstfeld_line / WFS (CSV) (csv)
[252/349] rad_rsp_radwege_forstfeld_line / WFS (GML) (xml)
[253/349] rad_rsp_radwege_forstfeld_line / Open Geodata Portal des Geoportals (html)
[254/349] rad_rsp_radwege_forstfeld_line / Metadaten (XML) (xml)
[255/349] deckschichten_opendata / Metadaten (XML) (xml)
[256/349] deckschichten_opendata / WFS (GML) (xml)
[257/349] deckschichten_opendata / WFS (CSV) (csv)
[258/349] deckschichten_opendata / Open Geodata Portal des Geoportals (html)
[259/349] kehrbezirke_opendata / Metadaten (XML) (xml)
[260/349] kehrbezirke_opendata / WFS (GML) (xml)
[261/349] kehrbezirke_opendata / WFS (CSV) (csv)
[262/349] kehrbezirke_opendata / Open Geodata Portal des Geoportals (html)
[263/349] qz_borkenkaefer / Metadaten (XML) (xml)
[264/349] qz_borkenkaefer / WFS (GML) (xml)
[265/349] qz_borkenkaefer / WFS (CSV) (csv)
[266/349] qz_borkenkaefer / Open Geodata Portal des Geoportals (html)
[267/349] rad_rsp_rad_freig_einbahn / WFS (CSV) (csv)
[268/349] rad_rsp_rad_freig_einbahn / WFS (GML) (xml)
[269/349] rad_rsp_rad_freig_einbahn / Open Geodata Portal des Geoportals (html)
[270/349] rad_rsp_rad_freig_einbahn / Metadaten (XML) (xml)
[271/349] baden_isar_opendata / Metadaten (XML) (xml)
[272/349] baden_isar_opendata / WFS (GML) (xml)
[273/349] baden_isar_opendata / WFS (CSV) (csv)
[274/349] baden_isar_opendata / Fachportal Isar (html)
[275/349] baden_isar_opendata / Fachportal OpenGeodata (html)
[276/349] stadtplan / Metadaten (XML) (xml)
[277/349] gefahrenstellen_isar_opendata / Metadaten (XML) (xml)
[278/349] gefahrenstellen_isar_opendata / WFS (GML) (xml)
[279/349] gefahrenstellen_isar_opendata / WFS (CSV) (csv)
[280/349] gefahrenstellen_isar_opendata / Fachportal Isar (html)
[281/349] gefahrenstellen_isar_opendata / Fachportal OpenGeodata (html)
[282/349] graustufenstadtplan_2024_geometrie / WMS (GetCapabilities) (html)
[283/349] graustufenstadtplan_2024_geometrie / Metadaten (XML) (xml)
[284/349] bootfahren_isar_opendata / Metadaten (XML) (xml)
[285/349] bootfahren_isar_opendata / WFS (CSV) (csv)
[286/349] bootfahren_isar_opendata / Fachportal Isar (html)
[287/349] bootfahren_isar_opendata / Fachportal OpenGeodata (html)
[288/349] bootfahren_isar_opendata / WFS (GML) (xml)
[289/349] rad_rsp_tempo30zone_poly / WFS (CSV) (csv)
[290/349] rad_rsp_tempo30zone_poly / WFS (GML) (xml)
[291/349] rad_rsp_tempo30zone_poly / Open Geodata Portal des Geoportals (html)
[292/349] rad_rsp_tempo30zone_poly / Metadaten (XML) (xml)
[293/349] baustellen_4_weeks_opendata / Metadaten (XML) (xml)
[294/349] baustellen_4_weeks_opendata / WFS (GML) (xml)
[295/349] baustellen_4_weeks_opendata / WFS (CSV) (csv)
[296/349] baustellen_4_weeks_opendata / Open Geodata Portal des Geoportals (html)
[297/349] baustellen_4_weeks_opendata / Fachportal Baustellen (html)
[298/349] erhalt_umgriff / Metadaten (XML) (xml)
[299/349] erhalt_umgriff / Open Geodata Portal des Geoportals (html)
[300/349] vagrund_baug_umgriff_opendata / Metadaten (XML) (xml)
[301/349] vagrund_baug_umgriff_opendata / Open Geodata Portal (html)
[302/349] vagrund_baug_umgriff_opendata / WFS (GML) (xml)
[303/349] vagrund_baug_umgriff_opendata / WFS (CSV) (csv)
[304/349] vablock_viertel_opendata / WFS (CSV) (csv)
[305/349] vablock_viertel_opendata / WFS (GML) (xml)
[306/349] vablock_viertel_opendata / Open Geodata Portal des Geoportals (html)
[307/349] vablock_viertel_opendata / Metadaten (XML) (xml)
[308/349] rad_rsp_fahrradstrasse_poly / WFS (CSV) (csv)
[309/349] rad_rsp_fahrradstrasse_poly / WFS (GML) (xml)
[310/349] rad_rsp_fahrradstrasse_poly / Open Geodata Portal des Geoportals (html)
[311/349] rad_rsp_fahrradstrasse_poly / Metadaten (XML) (xml)
[312/349] rad_rsp_fussg_zone_2024 / WFS (CSV) (csv)
[313/349] rad_rsp_fussg_zone_2024 / WFS (GML) (xml)
[314/349] rad_rsp_fussg_zone_2024 / Open Geodata Portal des Geoportals (html)
[315/349] rad_rsp_fussg_zone_2024 / Metadaten (XML) (xml)
[316/349] vablock_stadtbezirke_opendata / WFS (GML) (xml)
[317/349] vablock_stadtbezirke_opendata / WFS (CSV) (csv)

## Inspect extracted parameters

In [8]:
flat_rows = []
for entry in filter_catalog:
    for param in entry.get("filter_parameters", []):
        flat_rows.append({
            "package_name": entry["package_name"],
            "package_title": entry["package_title"],
            "resource_id": entry["resource_id"],
            "resource_name": entry["resource_name"],
            "format": entry["resource_format"],
            "filter_mode": param["filter_mode"],
            "server_filter_supported": param["server_filter_supported"],
            "column": param["column"],
            "dtype": param["dtype"],
            "kind": param["kind"],
            "operators": ",".join(param["operators"]),
            "example_values": json.dumps(param["example_values"], ensure_ascii=False),
            "min": param["min"],
            "max": param["max"],
        })

filter_df = pd.DataFrame(flat_rows)
print(f"filterable columns: {len(filter_df):,}")
filter_df.head(50)

filterable columns: 14,168

,package_name,package_title,resource_id,resource_name,format,filter_mode,server_filter_supported,column,dtype,kind,operators,example_values,min,max
0,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,_id,int64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""7"", ""8"", ""9"", ""10"", ""11"", ""12"", ""13"", ""14"", ""15"", ""16"", ""17"", ""18"", ""19"", ""20"", ""21"", ""22"", ""23"", ""24"", ""25""]",1.0,500.0
1,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Indikator,object,category,"eq,neq,in,contains","[""Wohndauer München""]",NaN,NaN
2,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Auspragung,object,category,"eq,neq,in,contains","[""deutsch""]",NaN,NaN
3,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Jahr,int64,year,"eq,neq,gt,gte,lt,lte,between,in","[""2025"", ""2024"", ""2023"", ""2022"", ""2021"", ""2020"", ""2019"", ""2018"", ""2017"", ""2016"", ""2015"", ""2014"", ""2013"", ""2012"", ""2011"", ""2010"", ""2009"", ""2008"", ""2007"", ""20...",2006.0,2025.0
4,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Raumbezug,object,category,"eq,neq,in,contains","[""Stadt München"", ""01 Altstadt - Lehel"", ""02 Ludwigsvorstadt - Isarvorstadt"", ""03 Maxvorstadt"", ""04 Schwabing - West"", ""05 Au - Haidhausen"", ""06 Sendling"", ...",NaN,NaN
5,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Indikatorwert,float64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""23.1"", ""23.0"", ""24.2"", ""22.9"", ""20.7"", ""22.8"", ""24.0"", ""24.4"", ""21.0"", ""21.1"", ""23.3"", ""22.6"", ""24.1"", ""22.4"", ""20.5"", ""22.0"", ""23.9"", ""24.6"", ""26.4"", ""22...",16.2,26.9
6,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Basiswert 1,object,string,"eq,neq,in,contains","[""1004727"", ""25521935"", ""294434"", ""659053"", ""654200"", ""1107220"", ""966967"", ""634556"", ""997497"", ""396287"", ""1643936"", ""919644"", ""1004373"", ""1179938"", ""1590577...",NaN,NaN
7,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Basiswert 2,object,string,"eq,neq,in,contains","[""40448"", ""15600"", ""68300"", ""70566"", ""40829"", ""75052"", ""1119484"", ""15583"", ""37098"", ""38498"", ""52749"", ""49064"", ""29955"", ""42947"", ""19595"", ""75466"", ""36558"", ...",NaN,NaN
8,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Name Basiswert 1,object,category,"eq,neq,in,contains","[""Summe (Wohndauer in München) (deutsch)""]",NaN,NaN
9,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Name Basiswert 2,object,category,"eq,neq,in,contains","[""Hauptwohnsitzbevölkerung (deutsch)""]",NaN,NaN
10,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.identifier,object,category,"eq,neq,in,contains","[""7d34eb9f-19a0-4bb0-b337-393b5a28bbe1""]",NaN,NaN
11,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.date,object,date,"eq,neq,gt,gte,lt,lte,between,in","[""2026-05-27T14:38:58""]",NaN,NaN
12,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.title,object,category,"eq,neq,in,contains","[""Solarpotenzialanalyse 2018 der Landeshauptstadt München""]",NaN,NaN
13,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.type,object,category,"eq,neq,in,contains","[""service""]",NaN,NaN
14,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.subject,object,category,"eq,neq,in,contains","[""Planungsunterlagen/Kataster""]",NaN,NaN
15,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.format,object,category,"eq,neq,in,contains","[""WMS""]",NaN,NaN
16,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.abstract,object,category,"eq,neq,in,contains","[""Basierend auf einem 3D-Modell, stellt die Solarpotenzialanalyse auf Grundlage von Ausrichtung, Neigung und Verschattung die einfallende Globalstrahlung in...",NaN,NaN
17,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.description,object,category,"eq,neq,in,contains","[""Basierend auf einem 3D-Modell, stellt die Solarpotenzialanalyse auf Grundlage von Ausrichtung, Neigung und Verschattung die einfallende Globalstrahlung in...",NaN,NaN
18,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.rights,object,category,"eq,neq,in,contains","[""otherRestrictions""]",NaN,NaN
19,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,Record.URI,object,category,"eq,neq,in,contains","[""https://geoportal.muenchen.de/portal/opendata""]",NaN,NaN
20,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,identifier,object,category,"eq,neq,in,contains","[""7d34eb9f-19a0-4bb0-b337-393b5a28bbe1""]",NaN,NaN
21,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,date,object,date,"eq,neq,gt,gte,lt,lte,between,in","[""2026-05-27T14:38:58""]",NaN,NaN
22,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,title,object,category,"eq,neq,in,contains","[""Solarpotenzialanalyse 2018 der Landeshauptstadt München""]",NaN,NaN
23,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,type,object,category,"eq,neq,in,contains","[""service""]",NaN,NaN
24,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,subject,object,category,"eq,neq,in,contains","[""Planungsunterlagen/Kataster""]",NaN,NaN
25,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,format,object,category,"eq,neq,in,contains","[""WMS""]",NaN,NaN
26,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,abstract,object,category,"eq,neq,in,contains","[""Basierend auf einem 3D-Modell, stellt die Solarpotenzialanalyse auf Grundlage von Ausrichtung, Neigung und Verschattung die einfallende Globalstrahlung in...",NaN,NaN
27,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,description,object,category,"eq,neq,in,contains","[""Basierend auf einem 3D-Modell, stellt die Solarpotenzialanalyse auf Grundlage von Ausrichtung, Neigung und Verschattung die einfallende Globalstrahlung in...",NaN,NaN
28,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,rights,object,category,"eq,neq,in,contains","[""otherRestrictions""]",NaN,NaN
29,solarpotenzial_globalstrahlung_p_02,Solarpotenzialanalyse 2018 der Landeshauptstadt München,160ad084-a469-4718-9d82-68ee8ccebdf9,Metadaten (XML),xml,local_dataframe,False,URI,object,category,"eq,neq,in,contains","[""https://geoportal.muenchen.de/portal/opendata""]",NaN,NaN
30,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.identifier,object,category,"eq,neq,in,contains","[""17a57e49-cf4b-46e2-b1da-66994505c699""]",NaN,NaN
31,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.date,object,date,"eq,neq,gt,gte,lt,lte,between,in","[""2026-05-27T14:39:13""]",NaN,NaN
32,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.title,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen (Opendata)""]",NaN,NaN
33,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.type,object,category,"eq,neq,in,contains","[""service""]",NaN,NaN
34,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.subject,object,category,"eq,neq,in,contains","[""infoMapAccessService""]",NaN,NaN
35,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.format,object,category,"eq,neq,in,contains","[""WMS""]",NaN,NaN
36,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.abstract,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen""]",NaN,NaN
37,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.description,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen""]",NaN,NaN
38,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.rights,object,category,"eq,neq,in,contains","[""otherRestrictions""]",NaN,NaN
39,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,Record.URI,object,category,"eq,neq,in,contains","[""https://geoportal.muenchen.de/portal/opendata""]",NaN,NaN
40,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,identifier,object,category,"eq,neq,in,contains","[""17a57e49-cf4b-46e2-b1da-66994505c699""]",NaN,NaN
41,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,date,object,date,"eq,neq,gt,gte,lt,lte,between,in","[""2026-05-27T14:39:13""]",NaN,NaN
42,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,title,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen (Opendata)""]",NaN,NaN
43,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,type,object,category,"eq,neq,in,contains","[""service""]",NaN,NaN
44,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,subject,object,category,"eq,neq,in,contains","[""infoMapAccessService""]",NaN,NaN
45,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,format,object,category,"eq,neq,in,contains","[""WMS""]",NaN,NaN
46,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,abstract,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen""]",NaN,NaN
47,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,description,object,category,"eq,neq,in,contains","[""Sonstige Abfallentsorgungsanlagen""]",NaN,NaN
48,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,rights,object,category,"eq,neq,in,contains","[""otherRestrictions""]",NaN,NaN
49,abfall_sonstiges_opendata,Sonstige Abfallentsorgungsanlagen (Opendata),ed5cf769-d6d1-4bfc-8073-9e742b10223e,Metadaten (XML),xml,local_dataframe,False,URI,object,category,"eq,neq,in,contains","[""https://geoportal.muenchen.de/portal/opendata""]",NaN,NaN

In [9]:
if not filter_df.empty:
    display(filter_df.groupby(["filter_mode", "kind"]).size().reset_index(name="columns").sort_values("columns", ascending=False))
    display(filter_df[filter_df["server_filter_supported"]].head(30))
else:
    print("No filter parameters extracted yet.")

        filter_mode      kind  columns
6   local_dataframe  category    12222
7   local_dataframe      date      750
8   local_dataframe   numeric      359
9   local_dataframe    string      344
10  local_dataframe      text      339
0    ckan_datastore  category       75
3    ckan_datastore    string       35
2    ckan_datastore   numeric       27
5    ckan_datastore      year       13
1    ckan_datastore      date        2
4    ckan_datastore      text        1
11  local_dataframe      year        1

,package_name,package_title,resource_id,resource_name,format,filter_mode,server_filter_supported,column,dtype,kind,operators,example_values,min,max
0,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,_id,int64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""7"", ""8"", ""9"", ""10"", ""11"", ""12"", ""13"", ""14"", ""15"", ""16"", ""17"", ""18"", ""19"", ""20"", ""21"", ""22"", ""23"", ""24"", ""25""]",1.00,500.00
1,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Indikator,object,category,"eq,neq,in,contains","[""Wohndauer München""]",NaN,NaN
2,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Auspragung,object,category,"eq,neq,in,contains","[""deutsch""]",NaN,NaN
3,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Jahr,int64,year,"eq,neq,gt,gte,lt,lte,between,in","[""2025"", ""2024"", ""2023"", ""2022"", ""2021"", ""2020"", ""2019"", ""2018"", ""2017"", ""2016"", ""2015"", ""2014"", ""2013"", ""2012"", ""2011"", ""2010"", ""2009"", ""2008"", ""2007"", ""20...",2006.00,2025.00
4,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Raumbezug,object,category,"eq,neq,in,contains","[""Stadt München"", ""01 Altstadt - Lehel"", ""02 Ludwigsvorstadt - Isarvorstadt"", ""03 Maxvorstadt"", ""04 Schwabing - West"", ""05 Au - Haidhausen"", ""06 Sendling"", ...",NaN,NaN
5,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Indikatorwert,float64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""23.1"", ""23.0"", ""24.2"", ""22.9"", ""20.7"", ""22.8"", ""24.0"", ""24.4"", ""21.0"", ""21.1"", ""23.3"", ""22.6"", ""24.1"", ""22.4"", ""20.5"", ""22.0"", ""23.9"", ""24.6"", ""26.4"", ""22...",16.20,26.90
6,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Basiswert 1,object,string,"eq,neq,in,contains","[""1004727"", ""25521935"", ""294434"", ""659053"", ""654200"", ""1107220"", ""966967"", ""634556"", ""997497"", ""396287"", ""1643936"", ""919644"", ""1004373"", ""1179938"", ""1590577...",NaN,NaN
7,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Basiswert 2,object,string,"eq,neq,in,contains","[""40448"", ""15600"", ""68300"", ""70566"", ""40829"", ""75052"", ""1119484"", ""15583"", ""37098"", ""38498"", ""52749"", ""49064"", ""29955"", ""42947"", ""19595"", ""75466"", ""36558"", ...",NaN,NaN
8,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Name Basiswert 1,object,category,"eq,neq,in,contains","[""Summe (Wohndauer in München) (deutsch)""]",NaN,NaN
9,indikatorenatlas-bevoelkerung-wohndauer-muenchen-83r65mct,Indikatorenatlas: Bevölkerung - Wohndauer München,773a81c6-1467-4c4a-adde-329776f4b44e,Wohndauer München,csv,ckan_datastore,True,Name Basiswert 2,object,category,"eq,neq,in,contains","[""Hauptwohnsitzbevölkerung (deutsch)""]",NaN,NaN
13983,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,_id,int64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""7"", ""8"", ""9"", ""10"", ""11"", ""12"", ""13"", ""14"", ""15"", ""16"", ""17"", ""18"", ""19"", ""20"", ""21"", ""22"", ""23"", ""24"", ""25""]",1.00,500.00
13984,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,Indikator,object,category,"eq,neq,in,contains","[""Zusammengefasste Geburtenrate""]",NaN,NaN
13985,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,Auspragung,object,category,"eq,neq,in,contains","[""deutsch""]",NaN,NaN
13986,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,Jahr,int64,year,"eq,neq,gt,gte,lt,lte,between,in","[""2025"", ""2024"", ""2023"", ""2022"", ""2021"", ""2020"", ""2019"", ""2018"", ""2017"", ""2016"", ""2015"", ""2014"", ""2013"", ""2012"", ""2011"", ""2010"", ""2009"", ""2008"", ""2007"", ""20...",2006.00,2025.00
13987,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,Raumbezug,object,category,"eq,neq,in,contains","[""Stadt München"", ""01 Altstadt - Lehel"", ""02 Ludwigsvorstadt - Isarvorstadt"", ""03 Maxvorstadt"", ""04 Schwabing - West"", ""05 Au - Haidhausen"", ""06 Sendling"", ...",NaN,NaN
13988,indikatorenatlas-bevoelkerung-zusammengefasste-geburtenrate-83r65mct,Indikatorenatlas: Bevölkerung - Zusammengefasste Geburtenrate,94a2515e-65cb-47be-b337-bdb0d01e853a,Zusammengefasste Geburtenrate,csv,ckan_datastore,True,Indikatorwert,float64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1.18"", ""1.08"", ""1.1"", ""1.12"", ""1.25"", ""1.16"", ""1.2"", ""1.27"", ""1.28"", ""1.13"", ""1.17"", ""1.24"", ""1.04"", ""1.15"", ""1.26"", ""1.05"", ""1.37"", ""1.19"", ""1.14"", ""1.07...",0.81,1.71
13989,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,_id,int64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""7"", ""8"", ""9"", ""10"", ""11"", ""12"", ""13"", ""14"", ""15"", ""16"", ""17"", ""18"", ""19"", ""20"", ""21"", ""22"", ""23"", ""24"", ""25""]",1.00,500.00
13990,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Indikator,object,category,"eq,neq,in,contains","[""Überalterungsquotient""]",NaN,NaN
13991,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Auspragung,object,category,"eq,neq,in,contains","[""deutsch""]",NaN,NaN
13992,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Jahr,int64,year,"eq,neq,gt,gte,lt,lte,between,in","[""2025"", ""2024"", ""2023"", ""2022"", ""2021"", ""2020"", ""2019"", ""2018"", ""2017"", ""2016"", ""2015"", ""2014"", ""2013"", ""2012"", ""2011"", ""2010"", ""2009"", ""2008"", ""2007"", ""20...",2006.00,2025.00
13993,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Raumbezug,object,category,"eq,neq,in,contains","[""Stadt München"", ""01 Altstadt - Lehel"", ""02 Ludwigsvorstadt - Isarvorstadt"", ""03 Maxvorstadt"", ""04 Schwabing - West"", ""05 Au - Haidhausen"", ""06 Sendling"", ...",NaN,NaN
13994,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Indikatorwert,float64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""156.3"", ""123.5"", ""125.8"", ""132.1"", ""121.5"", ""153.1"", ""118.3"", ""126.8"", ""138.4"", ""137.9"", ""144.8"", ""145.5"", ""161.1"", ""136.2"", ""132.4"", ""140.6"", ""112.5"", ""1...",70.90,225.60
13995,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Basiswert 1,object,string,"eq,neq,in,contains","[""8139"", ""7963"", ""2739"", ""9775"", ""7896"", ""7974"", ""8870"", ""4959"", ""9750"", ""4201"", ""9028"", ""2802"", ""9524"", ""220577"", ""2741"", ""4610"", ""4971"", ""9680"", ""7401"", ""...",NaN,NaN
13996,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Basiswert 2,object,string,"eq,neq,in,contains","[""7233"", ""6276"", ""6366"", ""5337"", ""5000"", ""3890"", ""10591"", ""4557"", ""6789"", ""5645"", ""5266"", ""4969"", ""5616"", ""5240"", ""3980"", ""4872"", ""4948"", ""165574"", ""1766"", ...",NaN,NaN
13997,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Name Basiswert 1,object,category,"eq,neq,in,contains","[""Hauptwohnsitzbevölkerung (65 Jahre und älter) (deutsch)""]",NaN,NaN
13998,indikatorenatlas-bevoelkerung-ueberalterungsquotient-83r65mct,Indikatorenatlas: Bevölkerung - Überalterungsquotient,fe9aeef9-3479-407c-b38f-db73a4dadf9f,Überalterungsquotient,csv,ckan_datastore,True,Name Basiswert 2,object,category,"eq,neq,in,contains","[""Hauptwohnsitzbevölkerung (bis 14 Jahre) (deutsch)""]",NaN,NaN
14041,veranstaltungen-der-messe-muenchen,Bisherige Veranstaltungen der Messe München,b698829c-b051-4092-a276-9ba1afdc12f3,Veranstaltungsdaten ab 2018,csv,ckan_datastore,True,_id,int64,numeric,"eq,neq,gt,gte,lt,lte,between,in","[""1"", ""2"", ""3"", ""4"", ""5"", ""6"", ""7"", ""8"", ""9"", ""10"", ""11"", ""12"", ""13"", ""14"", ""15"", ""16"", ""17"", ""18"", ""19"", ""20"", ""21"", ""22"", ""23"", ""24"", ""25""]",1.00,305.00
14042,veranstaltungen-der-messe-muenchen,Bisherige Veranstaltungen der Messe München,b698829c-b051-4092-a276-9ba1afdc12f3,Veranstaltungsdaten ab 2018,csv,ckan_datastore,True,langtitel,object,text,"contains,eq,neq","[""LASER World of PHOTONICS CHINA - International Trade Show for Optical Technologies in China"", ""productronica China - International Trade Fair for Electron...",NaN,NaN
14043,veranstaltungen-der-messe-muenchen,Bisherige Veranstaltungen der Messe München,b698829c-b051-4092-a276-9ba1afdc12f3,Veranstaltungsdaten ab 2018,csv,ckan_datastore,True,kurztitel,object,string,"eq,neq,in,contains","[""drink technology India"", ""LASER World of PHOTONICS INDIA"", ""LASER World of PHOTONICS CHINA"", ""productronica China"", ""INHORGENTA MUNICH"", ""LOPEC"", ""logitra...",NaN,NaN
14044,veranstaltungen-der-messe-muenchen,Bisherige Veranstaltungen der Messe München,b698829c-b051-4092-a276-9ba1afdc12f3,Veranstaltungsdaten ab 2018,csv,ckan_datastore,True,veranstaltungsjahr,object,category,"eq,neq,in,contains","[""2025"", ""2023"", ""2024"", ""2018"", ""2019"", ""2022"", ""2020"", ""2021"", ""2026""]",NaN,NaN

## Save artifacts

The JSONL file is the useful training-data source. The CSV file is for quick manual inspection.

In [10]:
jsonl_path = RAW_DATA_DIR / "munich_filter_parameters.jsonl"
csv_path = GENERATED_DATA_DIR / "munich_filter_parameters.csv"

with jsonl_path.open("w", encoding="utf-8") as file:
    for entry in filter_catalog:
        file.write(json.dumps(entry, ensure_ascii=False) + "\n")

filter_df.to_csv(csv_path, index=False)

jsonl_path, csv_path

(PosixPath('../training/data/raw/munich_filter_parameters.jsonl'),
 PosixPath('../training/data/generated/munich_filter_parameters.csv'))

## How to use this for training examples

Use each `filter_parameters` entry to generate examples for `generate_open_data_query` or `generate_dataframe_query`.

For example, a categorical parameter can create examples like:

```json
{
  "filters": [
    {"column": "geschlecht", "operator": "eq", "value": "w"}
  ],
  "sort": [{"column": "anzahl", "direction": "desc"}],
  "limit": 10
}
```

A numeric or year parameter can create range examples:

```json
{
  "filters": [
    {"column": "jahr", "operator": "between", "value": [2020, 2024]}
  ],
  "limit": 100
}
```

Remember: only datastore-backed resources should be described as API-filterable. CSV/XML/HTML parameters are still useful, but they are local dataframe filters after parsing.